# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bdcd0bbad166c99d5cc684985f02f29e94c4b41f628cbd439f35732cb174a637db404cae9855c9732fe2f806ae83caf07ba9d413ef91539680ef4c8c040a798

test:
  secret_key_base: 108ed0f375155073117a0d338918e90a753d3ee5656fa8460d7538dd17fdca94efd4f2f2809b470613b2cf8a574e21b1099af2be5cf066371d762e62aba41529

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
